# Generated by Django 4.0.3 on 2022-03-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_link',
        ),
    ]
