# Generated by Django 4.0.3 on 2022-03-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0002_category_alter_image_options_remove_image_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
