# Generated by Django 4.0.3 on 2022-03-26 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='picha.category'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_link',
            field=models.ImageField(default=None, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='picha.location'),
        ),
    ]
