# Generated by Django 4.0.3 on 2022-03-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0004_image_category_image_image_link_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='picha.category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='picha.location'),
        ),
    ]
