# Generated by Django 4.0.3 on 2022-03-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0005_alter_image_category_alter_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_link',
            field=models.ImageField(default=None, null=True, upload_to='image/'),
        ),
    ]
