# Generated by Django 4.0.3 on 2022-03-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0007_alter_image_options_remove_image_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name']},
        ),
    ]
