# Generated by Django 4.0.3 on 2022-03-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0014_alter_image_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
